### ISSUE TITLE
[Feature]: Allow full logging for functions or logs to be exported to a file

### ISSUE THREAD

**Issue by Hahlh** [Shopify/function-runner#260]
### What area(s) will this request affect?

Function

### What type of change do you want to see?

Substantial change to existing feature

### Overview

At the moment it seems not possible to get extensive logs out of test runs for Shopify functions (without executing the function directly via node) as they are always truncated:

![image](https://github.com/Shopify/cli/assets/45669613/680cb673-4e71-42be-bd31-b4038340f9ae)

It seems that a log functionality has existed once, but was removed without any alternative being introduced:
https://github.com/Shopify/cli/pull/969/ 

There also seem to be no command line options to prevent truncation neither for Javy nor for Shopify CLI directly. 

Are we simply missing something here? 
It seems full logging would be essential for function development. 
Having to adapt the function for direct execution with node every time we want to log intermediate steps feels like improvable DX. 

Thank you for your time.

Leo

### Motivation

Full logging is essential for function development and good DX.

**Comment by nickwesselman** [comment]
Can you provide more detail on the command that's being truncated here? `shopify app function run` ?

**Comment by nickwesselman** [comment]
@Hahlh Tagging you on the question above.

**Comment by andrewhassan** [comment]
I tried to reproduce this issue using `shopify app function run` by outputting a large amount of logs and output from a function. In both cases, the output isn't truncated in my terminal.

@Hahlh What command were you using when you experienced this issue?

**Comment by Hahlh** [comment]
Hey @nickwesselman , hey @andrewhassan, 

please excuse the long time of silence from my side. 

Because Andrew isn't able to reproduce the issue, I will close this issue for the moment until we have reproduced it again ourselves. 
If we are able to do so, I will also provide more context for you, so that you can properly debug, and reopen. 

We will get you more information by the end of the day. 

Thank you for staying committed to the investigation and resolution of this over this long period of time.
