### ISSUE TITLE
EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by matthewwren** [Shopify/function-runner#270]
What version? (`function-runner --version`): 5.0.0

## Problem

I get an error `EOF while parsing a value at line 1 column 0` when trying to run `function-runner`. I am on Windows 11.  I have tried a variety of things including using the Remix Template for the app and using the `products_discounts` template for the extension, and using JavaScript and TypeScript.  I have also tried using both empty and populated json input via both stdin and an input file.

## Error Message and Context
```
{
  "name": "function.wasm",
  "size": 2,
  "memory_usage": 0,
  "instructions": 100419,
  "logs": "",
  "output": {
    "InvalidJsonOutput": {
      "error": "EOF while parsing a value at line 1 column 0",
      "stdout": ""
    }
  }
}
```

## Steps to reproduce
- In terminal I run `shopify app init`
- I accept the default app name by pressing `tab`
- I select `Start by adding your first extension`
- I `cd` to app directory
- I run `shopify app generate extension`
- I select `y` to create as a new app
- I accept the default app name by pressing `tab`
- I select `Cart transformer`
- I accept the default name by pressing `tab`
- I select `TypeScript`
- I run `shopify app dev`
- I select my dev store
- I click the preview url and click the `Install` button
- I then `cd` to the `dist` folder of the extension
- I run `echo '{}' | function-runner --function function.wasm --json`

**Comment by meditto** [comment]
> I have the same issue

we have to specify the name of the export we want to invoke, I fixed my issue by adding this ```-e run```

**Comment by DuncanUszkay1** [comment]
Apologies, forg

**Comment by mariusa** [comment]
@DuncanUszkay1 getting the same with version 8.0.1. Adding the export fixes it.
